cars/cars/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("web.urls")),
]

cars/web/urls.py
from django.urls import path

from web.views import (
    DriveDetail,
    CarDriveEdit,
    AnalysisCreate,
    CarDriveFileList,
    DataFileDetail,
    CarTypeList,
)

urlpatterns = [
    path("", DataFileDetail.as_view(), name="file_detail"),
    path("analysis/create", AnalysisCreate.as_view(), name="analysis_create"),
    path("cars", CarDriveFileList.as_view(), name="cars_file_detail"),
    path("cartypes", CarTypeList.as_view(), name="cars_types_list"),
    path("car/<int:pk>", CarDriveEdit.as_view(), name="cars_file_update"),
    path("drive/<int:pk>", DriveDetail.as_view(), name="drive_detail"),
]

cars/web/models.py
# Create your models here.
from django.contrib.gis.db.models import PointField
from django.db import models
from django.urls import reverse

Manufacturers = models.TextChoices("Manufacturers", "SKODA VW")
EngineTypes = models.TextChoices("EngineTypes", "GAS DIESEL ELECTRIC HYBRID")


class CarTypes(models.Model):
    name = models.CharField(max_length=128)
    manufacturer = models.CharField(choices=Manufacturers.choices)
    engine_type = models.CharField(choices=EngineTypes.choices)
    emissions_fuel_per_km = models.PositiveIntegerField(default=0)
    max_range_km = models.PositiveIntegerField(default=0)
    cost_new = models.PositiveIntegerField(default=0)

    @property
    def range(self):
        if self.engine_type == EngineTypes.ELECTRIC:
            return self.max_range_km

        return float("inf")

    def __str__(self):
        return f"{self.manufacturer} {self.name}"


# class DataFile(models.Model):
#     file_name = models.CharField()


class CarDrive(models.Model):
    license_plate = models.CharField()
    type = models.ForeignKey(
        CarTypes,
        on_delete=models.CASCADE,
        null=True,
    )
    proposed_type = models.ForeignKey(
        CarTypes,
        on_delete=models.CASCADE,
        null=True,
        default=None,
        related_name="proposed",
        blank=True,
    )
    # file = models.ForeignKey(DataFile, on_delete=models.CASCADE, related_name="cars")
    # odometer_km = models.IntegerField(default=0)
    year_made = models.DateTimeField()
    frozen = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.license_plate} - {self.type}"

    def get_absolute_url(self):
        return reverse("cars_file_update", args=[str(self.id)])


class Drive(models.Model):
    # file = models.ForeignKey(DataFile, on_delete=models.CASCADE, related_name="drives")
    car = models.ForeignKey(CarDrive, on_delete=models.CASCADE, related_name="drives")

    # distance_km = models.PositiveIntegerField()
    # odometer_end_km = models.IntegerField()

    location_start = PointField()
    location_stop = PointField()

    # time_start = models.DateTimeField()
    # time_stop = models.DateTimeField()


class Analysis(models.Model):
    # file = models.ForeignKey(DataFile, on_delete=models.CASCADE, related_name="analysis")

    replace_min_age_years = models.PositiveIntegerField()
    replace_min_odometer_km = models.PositiveIntegerField()
    max_range_margin_km = models.PositiveIntegerField(default=0)

cars/web/templates/analysis_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="row">

        <!-- Area Chart -->
        <div class="col-lg-12">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Run analysis on company fleet</h6>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <p>
                                Here you can run analysis on company car fleet based on following values.
                            </p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-12">
                            <form method="POST">
                                {% csrf_token %}
                                {{ form|crispy }}
                                <button type="submit">Save</button>
                            </form>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>



    {#    <div class="row">#}
    {#        <div class="col-md-12">#}
    {#            <div class="card shadow mb-4">#}
    {#                <div class="card-header py-3">#}
    {#                    <h6 class="m-0 font-weight-bold text-primary">List of trips made by the car</h6>#}
    {#                </div>#}
    {#                <div class="card-body">#}
    {#                    <div class="table-responsive">#}
    {#                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">#}
    {#                            <thead>#}
    {#                            <tr>#}
    {#                                <th>ID</th>#}
    {#                                <th>Distance</th>#}
    {#                            </tr>#}
    {#                            </thead>#}
    {#                            <tfoot>#}
    {#                            <tr>#}
    {#                                <th>ID</th>#}
    {#                                <th>Distance</th>#}
    {#                            </tr>#}
    {#                            </tfoot>#}
    {#                            <tbody>#}
    {#                            {% for drive in object.drives.all %}#}
    {#                                <tr>#}
    {#                                    <td><a href="">{{ drive.id }}</a></td>#}
    {#                                    <td>{{ drive.distance.km|floatformat:0 }} km</td>#}
    {#                                </tr>#}
    {#                            {% endfor %}#}
    {#                            </tbody>#}
    {#                        </table>#}
    {#                    </div>#}
    {#                </div>#}
    {#            </div>#}
    {#        </div>#}
    {#    </div>#}
{% endblock %}

cars/web/templates/car_type_list.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">List of all cars in the fleet</h6>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-lg-12">
                    <p>
                        Following cars are considered as replacement in company fleet.
                    </p>
                </div>
            </div>
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>Name</th>
                        <th>Manufacturer</th>
                        <th>Engine type</th>
                        <th>CO2 emissions</th>
                        <th>Range</th>
                        <th>Cost</th>
                    </tr>
                    </thead>
                    <tfoot>
                    <tr>
                        <th>Name</th>
                        <th>Manufacturer</th>
                        <th>Engine type</th>
                        <th>CO2 emissions</th>
                        <th>Range</th>
                        <th>Cost</th>
                    </tfoot>
                    <tbody>
                    {% for car in object_list %}
                        <tr>
                            <td>{{ car.name }}</td>
                            <td>{{ car.get_manufacturer_display }}</td>
                            <td>{{ car.get_engine_type_display }}</td>
                            <td>{% if car.engine_type != "ELECTRIC" %}{{ car.emissions_fuel_per_km }} g/Km{% endif %}</td>
                            <td>{% if car.engine_type == "ELECTRIC" %}{{ car.range }} Km{% endif %}</td>
                            <td>{{ car.cost_new|intcomma }} Kc</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}

cars/web/templates/data_file_cars_detail.html
{% extends 'base.html' %}
{% load humanize %}
{% block content %}
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">List of all cars in the fleet</h6>
        </div>
        <div class="card-body">
            <div class="row">
                <div class="col-lg-12">
                    <p>
                        This list shows company feet with proposed replacement cars.
                        <b>Proposed tCO2</b> is computed on assumption that same trips care made in history would be
                        made with a replacement car.
                        <b>Longest trip</b> is used to find suitable car which must be able to make this trip on a
                        single charge.
                        If no suitable electric car can be found, petrol car is used.
                    </p>
                </div>
            </div>
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>ID</th>
                        <th>Original Car</th>
                        <th>Original tCO2</th>
                        <th>Proposed Car</th>
                        <th>Proposed tCO2</th>
                        <th>Total distance</th>
                        <th>Longest trip</th>
                        <th>Year made</th>
                        <th>Frozen</th>
                    </tr>
                    </thead>
                    <tfoot>
                    <tr>
                        <th>ID</th>
                        <th>Original Car</th>
                        <th>Original tCO2</th>
                        <th>Proposed Car</th>
                        <th>Proposed tCO2</th>
                        <th>Total distance</th>
                        <th>Longest trip</th>
                        <th>Year made</th>
                        <th>Frozen</th>
                    </tfoot>
                    <tbody>
                    {% for car in object_list %}
                        <tr>
                            <td><a href="{% url 'cars_file_update' pk=car.id %}">{{ car.license_plate }}</a></td>
                            <td style="background-color: #e7ffc7">{{ car.type.name }} {{ car.type.engine_type }}</td>
                            <td style="background-color: #d5ff9e">{{ car.original_emissions_total_t|floatformat:2 }}</td>
                            <td style="background-color: #cfe1fa">
                                {{ car.proposed_type.name }} {{ car.proposed_type.engine_type }}
                                {% if car.proposed_type.engine_type ==  "ELECTRIC" %} ♻️ {% endif %}
                                {% if car.proposed_type.engine_type ==  "DIESEL" %} 🔥 {% endif %}
                                {% if car.proposed_type.engine_type ==  "GAS" %} 🕯️ {% endif %}
                                {% if car.proposed_type.engine_type ==  "HYBRID" %} ☯️️ {% endif %}
                                {% if not car.proposed_type %} Removed ❌ {% endif %}
                            </td>
                            <td style="background-color: #b3d2fc">{{ car.proposed_emissions_total_t|floatformat:2 }}</td>
                            <td>{{ car.distance_total.km |floatformat:0 }} km</td>
                            <td>{{ car.distance_max.km |floatformat:0 }} km</td>
                            <td>{{ car.year_made.year }}</td>
                            <td>{% if car.frozen %}🔒{% endif %}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>


    <!-- Pie Chart -->
    {#        <div class="col-xl-4 col-lg-5">#}
    {#            <div class="card shadow mb-4">#}
    {#                <!-- Card Header - Dropdown -->#}
    {#                <div#}
    {#                        class="card-header py-3 d-flex flex-row align-items-center justify-content-between">#}
    {#                    <h6 class="m-0 font-weight-bold text-primary">Revenue Sources</h6>#}
    {##}
    {#                </div>#}
    {#                <!-- Card Body -->#}
    {#                <div class="card-body">#}
    {#                    <div class="chart-pie pt-4 pb-2">#}
    {#                        <canvas id="myPieChart"></canvas>#}
    {#                    </div>#}
    {#                    <div class="mt-4 text-center small">#}
    {#                                        <span class="mr-2">#}
    {#                                            <i class="fas fa-circle text-primary"></i> Direct#}
    {#                                        </span>#}
    {#                        <span class="mr-2">#}
    {#                                            <i class="fas fa-circle text-success"></i> Social#}
    {#                                        </span>#}
    {#                        <span class="mr-2">#}
    {#                                            <i class="fas fa-circle text-info"></i> Referral#}
    {#                                        </span>#}
    {#                    </div>#}
    {#                </div>#}
    {#            </div>#}
    {#        </div>#}
    {#</div>#}

{% endblock %}

cars/web/templates/data_file_cars_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="row">

        <!-- Area Chart -->
        <div class="col-lg-12">
            <div class="card shadow mb-4">
                <!-- Card Header - Dropdown -->
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                    <h6 class="m-0 font-weight-bold text-primary">Car {{ object.license_plate }}</h6>
                </div>
                <!-- Card Body -->
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-12">
                        <form method="POST">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <button type="submit">Save</button>
                        </form>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>



    {#    <div class="row">#}
    {#        <div class="col-md-12">#}
    {#            <div class="card shadow mb-4">#}
    {#                <div class="card-header py-3">#}
    {#                    <h6 class="m-0 font-weight-bold text-primary">List of trips made by the car</h6>#}
    {#                </div>#}
    {#                <div class="card-body">#}
    {#                    <div class="table-responsive">#}
    {#                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">#}
    {#                            <thead>#}
    {#                            <tr>#}
    {#                                <th>ID</th>#}
    {#                                <th>Distance</th>#}
    {#                            </tr>#}
    {#                            </thead>#}
    {#                            <tfoot>#}
    {#                            <tr>#}
    {#                                <th>ID</th>#}
    {#                                <th>Distance</th>#}
    {#                            </tr>#}
    {#                            </tfoot>#}
    {#                            <tbody>#}
    {#                            {% for drive in object.drives.all %}#}
    {#                                <tr>#}
    {#                                    <td><a href="">{{ drive.id }}</a></td>#}
    {#                                    <td>{{ drive.distance.km|floatformat:0 }} km</td>#}
    {#                                </tr>#}
    {#                            {% endfor %}#}
    {#                            </tbody>#}
    {#                        </table>#}
    {#                    </div>#}
    {#                </div>#}
    {#            </div>#}
    {#        </div>#}
    {#    </div>#}
{% endblock %}

cars/web/templates/fonts.html
{% load static %}

<style>
    /* nunito-regular - cyrillic_cyrillic-ext_latin_latin-ext */
    /* nunito-200 - cyrillic_cyrillic-ext_latin_latin-ext */
    @font-face {
      font-display: swap; /* Check https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display for other options. */
      font-family: 'Nunito';
      font-style: normal;
      font-weight: 200;
      src: url('{% static 'fonts/nunito-v25-cyrillic_cyrillic-ext_latin_latin-ext-200.woff2' %}') format('woff2'), /* Chrome 36+, Opera 23+, Firefox 39+ */
           url('{% static 'fonts/nunito-v25-cyrillic_cyrillic-ext_latin_latin-ext-200.woff' %}') format('woff'); /* Chrome 5+, Firefox 3.6+, IE 9+, Safari 5.1+ */
    }

    /* nunito-200italic - cyrillic_cyrillic-ext_latin_latin-ext */
    @font-face {
      font-display: swap; /* Check https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display for other options. */
      font-family: 'Nunito';
      font-style: italic;
      font-weight: 200;
      src: url('{% static 'fonts/nunito-v25-cyrillic_cyrillic-ext_latin_latin-ext-200italic.woff2' %}') format('woff2'), /* Chrome 36+, Opera 23+, Firefox 39+ */
           url('{% static 'fonts/nunito-v25-cyrillic_cyrillic-ext_latin_latin-ext-200italic.woff' %}') format('woff'); /* Chrome 5+, Firefox 3.6+, IE 9+, Safari 5.1+ */
    }



    /* nunito-300 - cyrillic_cyrillic-ext_latin_latin-ext */
    @font-face {
      font-display: swap; /* Check https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display for other options. */
      font-family: 'Nunito';
      font-style: normal;
      font-weight: 300;
      src: url('{% static 'fonts/nunito-v25-cyrillic_cyrillic-ext_latin_latin-ext-300.woff2' %}') format('woff2'), /* Chrome 36+, Opera 23+, Firefox 39+ */
           url('{% static 'fonts/nunito-v25-cyrillic_cyrillic-ext_latin_latin-ext-300.woff' %}') format('woff'); /* Chrome 5+, Firefox 3.6+, IE 9+, Safari 5.1+ */
    }


    /* nunito-300italic - cyrillic_cyrillic-ext_latin_latin-ext */
    @font-face {
      font-display: swap; /* Check https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display for other options. */
      font-family: 'Nunito';
      font-style: italic;
      font-weight: 300;
      src: url('{% static 'fonts/nunito-v25-cyrillic_cyrillic-ext_latin_latin-ext-300italic.woff2' %}') format('woff2'), /* Chrome 36+, Opera 23+, Firefox 39+ */
           url('{% static 'fonts/nunito-v25-cyrillic_cyrillic-ext_latin_latin-ext-300italic.woff' %}') format('woff'); /* Chrome 5+, Firefox 3.6+, IE 9+, Safari 5.1+ */
    }


    /* nunito-regular - cyrillic_cyrillic-ext_latin_latin-ext */
    @font-face {
      font-display: swap; /* Check https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display for other options. */
      font-family: 'Nunito';
      font-style: normal;
      font-weight: 400;
      src: url('{% static 'fonts/nunito-v25-cyrillic_cyrillic-ext_latin_latin-ext-regular.woff2' %}') format('woff2'), /* Chrome 36+, Opera 23+, Firefox 39+ */
           url('{% static 'fonts/nunito-v25-cyrillic_cyrillic-ext_latin_latin-ext-regular.woff' %}') format('woff'); /* Chrome 5+, Firefox 3.6+, IE 9+, Safari 5.1+ */
    }


    /* nunito-italic - cyrillic_cyrillic-ext_latin_latin-ext */
    @font-face {
      font-display: swap; /* Check https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display for other options. */
      font-family: 'Nunito';
      font-style: italic;
      font-weight: 400;
      src: url('{% static 'fonts/nunito-v25-cyrillic_cyrillic-ext_latin_latin-ext-italic.woff2' %}') format('woff2'), /* Chrome 36+, Opera 23+, Firefox 39+ */
           url('{% static 'fonts/nunito-v25-cyrillic_cyrillic-ext_latin_latin-ext-italic.woff' %}') format('woff'); /* Chrome 5+, Firefox 3.6+, IE 9+, Safari 5.1+ */
    }


    /* nunito-500 - cyrillic_cyrillic-ext_latin_latin-ext */
    @font-face {
      font-display: swap; /* Check https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display for other options. */
      font-family: 'Nunito';
      font-style: normal;
      font-weight: 500;
      src: url('{% static 'fonts/nunito-v25-cyrillic_cyrillic-ext_latin_latin-ext-500.woff2' %}') format('woff2'), /* Chrome 36+, Opera 23+, Firefox 39+ */
           url('{% static 'fonts/nunito-v25-cyrillic_cyrillic-ext_latin_latin-ext-500.woff' %}') format('woff'); /* Chrome 5+, Firefox 3.6+, IE 9+, Safari 5.1+ */
    }

    /* nunito-500italic - cyrillic_cyrillic-ext_latin_latin-ext */
    @font-face {
      font-display: swap; /* Check https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display for other options. */
      font-family: 'Nunito';
      font-style: italic;
      font-weight: 500;
      src: url('{% static 'fonts/nunito-v25-cyrillic_cyrillic-ext_latin_latin-ext-500italic.woff2' %}') format('woff2'), /* Chrome 36+, Opera 23+, Firefox 39+ */
           url('{% static 'fonts/nunito-v25-cyrillic_cyrillic-ext_latin_latin-ext-500italic.woff' %}') format('woff'); /* Chrome 5+, Firefox 3.6+, IE 9+, Safari 5.1+ */
    }


    /* nunito-600 - cyrillic_cyrillic-ext_latin_latin-ext */
    @font-face {
      font-display: swap; /* Check https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display for other options. */
      font-family: 'Nunito';
      font-style: normal;
      font-weight: 600;
      src: url('{% static 'fonts/nunito-v25-cyrillic_cyrillic-ext_latin_latin-ext-600.woff2' %}') format('woff2'), /* Chrome 36+, Opera 23+, Firefox 39+ */
           url('{% static 'fonts/nunito-v25-cyrillic_cyrillic-ext_latin_latin-ext-600.woff' %}') format('woff'); /* Chrome 5+, Firefox 3.6+, IE 9+, Safari 5.1+ */
    }


    /* nunito-600italic - cyrillic_cyrillic-ext_latin_latin-ext */
    @font-face {
      font-display: swap; /* Check https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display for other options. */
      font-family: 'Nunito';
      font-style: italic;
      font-weight: 600;
      src: url('{% static 'fonts/nunito-v25-cyrillic_cyrillic-ext_latin_latin-ext-600italic.woff2' %}') format('woff2'), /* Chrome 36+, Opera 23+, Firefox 39+ */
           url('{% static 'fonts/nunito-v25-cyrillic_cyrillic-ext_latin_latin-ext-600italic.woff' %}') format('woff'); /* Chrome 5+, Firefox 3.6+, IE 9+, Safari 5.1+ */
    }


    /* nunito-700 - cyrillic_cyrillic-ext_latin_latin-ext */
    @font-face {
      font-display: swap; /* Check https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display for other options. */
      font-family: 'Nunito';
      font-style: normal;
      font-weight: 700;
      src: url('{% static 'fonts/nunito-v25-cyrillic_cyrillic-ext_latin_latin-ext-700.woff2' %}') format('woff2'), /* Chrome 36+, Opera 23+, Firefox 39+ */
           url('{% static 'fonts/nunito-v25-cyrillic_cyrillic-ext_latin_latin-ext-700.woff' %}') format('woff'); /* Chrome 5+, Firefox 3.6+, IE 9+, Safari 5.1+ */
    }


    /* nunito-700italic - cyrillic_cyrillic-ext_latin_latin-ext */
    @font-face {
      font-display: swap; /* Check https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display for other options. */
      font-family: 'Nunito';
      font-style: italic;
      font-weight: 700;
      src: url('{% static 'fonts/nunito-v25-cyrillic_cyrillic-ext_latin_latin-ext-700italic.woff2' %}') format('woff2'), /* Chrome 36+, Opera 23+, Firefox 39+ */
           url('{% static 'fonts/nunito-v25-cyrillic_cyrillic-ext_latin_latin-ext-700italic.woff' %}') format('woff'); /* Chrome 5+, Firefox 3.6+, IE 9+, Safari 5.1+ */
    }



    /* nunito-800 - cyrillic_cyrillic-ext_latin_latin-ext */
    @font-face {
      font-display: swap; /* Check https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display for other options. */
      font-family: 'Nunito';
      font-style: normal;
      font-weight: 800;
      src: url('{% static 'fonts/nunito-v25-cyrillic_cyrillic-ext_latin_latin-ext-800.woff2' %}') format('woff2'), /* Chrome 36+, Opera 23+, Firefox 39+ */
           url('{% static 'fonts/nunito-v25-cyrillic_cyrillic-ext_latin_latin-ext-800.woff' %}') format('woff'); /* Chrome 5+, Firefox 3.6+, IE 9+, Safari 5.1+ */
    }

    /* nunito-800italic - cyrillic_cyrillic-ext_latin_latin-ext */
    @font-face {
      font-display: swap; /* Check https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display for other options. */
      font-family: 'Nunito';
      font-style: italic;
      font-weight: 800;
      src: url('{% static 'fonts/nunito-v25-cyrillic_cyrillic-ext_latin_latin-ext-800italic.woff2' %}') format('woff2'), /* Chrome 36+, Opera 23+, Firefox 39+ */
           url('{% static 'fonts/nunito-v25-cyrillic_cyrillic-ext_latin_latin-ext-800italic.woff' %}') format('woff'); /* Chrome 5+, Firefox 3.6+, IE 9+, Safari 5.1+ */
    }

    /* nunito-900 - cyrillic_cyrillic-ext_latin_latin-ext */
    @font-face {
      font-display: swap; /* Check https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display for other options. */
      font-family: 'Nunito';
      font-style: normal;
      font-weight: 900;
      src: url('{% static 'fonts/nunito-v25-cyrillic_cyrillic-ext_latin_latin-ext-900.woff2' %}') format('woff2'), /* Chrome 36+, Opera 23+, Firefox 39+ */
           url('{% static 'fonts/nunito-v25-cyrillic_cyrillic-ext_latin_latin-ext-900.woff' %}') format('woff'); /* Chrome 5+, Firefox 3.6+, IE 9+, Safari 5.1+ */
    }


    /* nunito-900italic - cyrillic_cyrillic-ext_latin_latin-ext */
    @font-face {
      font-display: swap; /* Check https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display for other options. */
      font-family: 'Nunito';
      font-style: italic;
      font-weight: 900;
      src: url('{% static 'fonts/nunito-v25-cyrillic_cyrillic-ext_latin_latin-ext-900italic.woff2' %}') format('woff2'), /* Chrome 36+, Opera 23+, Firefox 39+ */
           url('{% static 'fonts/nunito-v25-cyrillic_cyrillic-ext_latin_latin-ext-900italic.woff' %}') format('woff'); /* Chrome 5+, Firefox 3.6+, IE 9+, Safari 5.1+ */
    }
</style>